AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  predict-api

  Sample SAM Template for predict-api

Globals:
  Function:
    Timeout: 10

Resources:
  InferenceApi:
    Type: AWS::Serverless::Api
    Properties:
     StageName: Prod

  InferenceFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Events:
        Inference:
          Type: Api 
          Properties:
            Path: /classification
            Method: post
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./
      Dockerfile: Dockerfile


Outputs:
  InferenceFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt InferenceFunction.Arn
  InferenceFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt InferenceFunctionRole.Arn

