AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  alkaloid-api

  Sample SAM Template for alkaloid-api

Globals:
  Function:
    Timeout: 10

Resources:
  AlkaloidApi:
    Type: AWS::Serverless::Api
    Properties:
     StageName: Prod

  AlkaloidFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: Alkaloid
      PackageType: Image
      Events:
        Inference:
          Type: Api 
          Properties:
            RestApiId: !Ref AlkaloidApi
            Path: /classification
            Method: post
    Metadata:
      DockerTag: python3.7-v1
      DockerContext: ./
      Dockerfile: Dockerfile


Outputs:
  AlkaloidFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt AlkaloidFunction.Arn
  AlkaloidFunctionIamRole:
    Description: "Implicit IAM Role created for function"
    Value: !GetAtt AlkaloidFunctionRole.Arn
